server:
    port: 9001
#   address=<another IP address>
#   sessionTimeout=<another timeout setting>
#   contextPath=/your-other-path

spring:
    datasource:
        url: jdbc:postgresql://localhost/test
        username: root
        password: changeme
        driverClassName: org.postgresql.Driver
        schema: