server:
    port: 8080
#   address=<another IP address>
#   sessionTimeout=<another timeout setting>
#   contextPath=/your-other-path

spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:test;MODE=PostgreSQL
#   schema: classpath:/data.sql
